# Generated by Django 3.1.2 on 2020-10-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201013_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='descreption',
        ),
    ]
